export const factsData = [
    { category: "SPACE", fact: "A day on Venus is longer than its year. Venus rotates so slowly that one day (243 Earth days) is longer than one year (225 Earth days)." },
    { category: "SPACE", fact: "There are more possible games of chess than there are atoms in the observable universe." },
    { category: "SPACE", fact: "Jupiter's Great Red Spot is a storm that has been raging for at least 400 years and could fit three Earths inside it." },
    { category: "SPACE", fact: "Neutron stars are so dense that a teaspoon of neutron star material would weigh about 6 billion tons." },
    { category: "SPACE", fact: "Saturn's moon Titan has lakes and rivers made of liquid methane and ethane." },
    { category: "SPACE", fact: "The Sun converts 4 million tons of mass into energy every second through nuclear fusion." },
    { category: "SPACE", fact: "Mercury experiences temperature swings of over 1,100 degrees Fahrenheit between day and night." },
    { category: "SPACE", fact: "The Milky Way galaxy is on a collision course with the Andromeda galaxy, set to collide in 4.5 billion years." },
    { category: "SPACE", fact: "Mars has the largest volcano in the solar system, Olympus Mons, which is 16 miles high." },
    { category: "SPACE", fact: "Europa, Jupiter's moon, has more water than all of Earth's oceans combined beneath its icy surface." },
    { category: "SPACE", fact: "The footprints left by Apollo astronauts on the Moon will remain there for millions of years due to no atmosphere." },
    { category: "SPACE", fact: "Pluto takes 248 Earth years to complete one orbit around the Sun." },
    { category: "SPACE", fact: "The International Space Station travels at 17,500 mph and orbits Earth every 90 minutes." },
    { category: "SPACE", fact: "Uranus rotates on its side, likely due to a massive collision early in its history." },
    { category: "SPACE", fact: "Black holes can have temperatures lower than outer space, making them the coldest objects in the universe." },
    { category: "SPACE", fact: "The Moon is moving away from Earth at a rate of about 1.5 inches per year." },
    { category: "SPACE", fact: "One year on Neptune equals 165 Earth years." },
    { category: "SPACE", fact: "The Asteroid Belt contains less mass than Earth's Moon despite spanning millions of miles." },
    { category: "SPACE", fact: "Ganymede, Jupiter's largest moon, has its own magnetic field and is larger than Mercury." },
    { category: "SPACE", fact: "The solar wind travels at speeds of up to 1.8 million miles per hour." },

    { category: "NATURE", fact: "Octopuses have three hearts and blue blood. Two hearts pump blood to the gills, while the third pumps blood to the rest of the body." },
    { category: "NATURE", fact: "Bamboo is the fastest-growing plant on Earth, capable of growing up to 35 inches in a single day." },
    { category: "NATURE", fact: "A single cloud can weigh over one million pounds despite appearing to float effortlessly." },
    { category: "NATURE", fact: "Lightning strikes the Earth about 100 times per second, or 8.6 million times per day." },
    { category: "NATURE", fact: "Redwood trees can live for over 2,000 years and grow taller than a 30-story building." },
    { category: "NATURE", fact: "A bolt of lightning is five times hotter than the surface of the Sun." },
    { category: "NATURE", fact: "Raindrops aren't actually teardrop-shaped; they're more like hamburger buns due to air resistance." },
    { category: "NATURE", fact: "Antarctica contains 70% of the world's fresh water and 90% of the world's ice." },
    { category: "NATURE", fact: "The Amazon rainforest produces about 20% of the world's oxygen." },
    { category: "NATURE", fact: "Mushrooms are more closely related to humans than to plants." },
    { category: "NATURE", fact: "A single raindrop can contain up to one million bacteria." },
    { category: "NATURE", fact: "The Great Barrier Reef is the largest living structure on Earth and can be seen from space." },
    { category: "NATURE", fact: "Trees can communicate with each other through an underground network of fungi called the 'wood wide web'." },
    { category: "NATURE", fact: "Hurricanes release the energy equivalent of a 10-megaton nuclear bomb every 20 minutes." },
    { category: "NATURE", fact: "The oldest living tree is over 5,000 years old and is located in California." },
    { category: "NATURE", fact: "Volcanic lightning occurs when ash particles in a volcanic plume create electrical charges." },
    { category: "NATURE", fact: "The deepest point on Earth is the Mariana Trench, which is deeper than Mount Everest is tall." },
    { category: "NATURE", fact: "Some plants can live for thousands of years, while others complete their entire life cycle in just a few weeks." },
    { category: "NATURE", fact: "The Northern Lights are caused by solar particles colliding with gases in Earth's atmosphere." },
    { category: "NATURE", fact: "A single large tree can absorb 40 pounds of carbon dioxide per year." },

    { category: "HISTORY", fact: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza." },
    { category: "HISTORY", fact: "The Great Wall of China isn't visible from space with the naked eye, contrary to popular belief." },
    { category: "HISTORY", fact: "Oxford University is older than the Aztec Empire by over 200 years." },
    { category: "HISTORY", fact: "Napoleon was actually average height for his time at 5'7\", not short as commonly believed." },
    { category: "HISTORY", fact: "The shortest war in history lasted only 38-45 minutes between Britain and Zanzibar in 1896." },
    { category: "HISTORY", fact: "Woolly mammoths were still alive when the Great Pyramid was built." },
    { category: "HISTORY", fact: "The Roman Empire lasted for over 1,000 years, from 27 BC to 1453 AD." },
    { category: "HISTORY", fact: "Vikings never actually wore horned helmets; this is a modern myth popularized by opera." },
    { category: "HISTORY", fact: "The Mona Lisa was stolen in 1911 and wasn't recovered until 1913." },
    { category: "HISTORY", fact: "Ancient Romans used urine as mouthwash because ammonia whitens teeth." },
    { category: "HISTORY", fact: "The Berlin Wall fell in 1989, just 28 years after it was built." },
    { category: "HISTORY", fact: "Stonehenge is older than the Egyptian pyramids by several hundred years." },
    { category: "HISTORY", fact: "The Titanic's wreckage wasn't discovered until 1985, 73 years after it sank." },
    { category: "HISTORY", fact: "Genghis Khan's empire was four times larger than Alexander the Great's empire." },
    { category: "HISTORY", fact: "The printing press wasn't invented until 1440, over 1,000 years after paper was invented." },
    { category: "HISTORY", fact: "Marie Curie is the only person to win Nobel Prizes in two different scientific fields." },
    { category: "HISTORY", fact: "The first Olympic Games were held in 776 BC in ancient Greece." },
    { category: "HISTORY", fact: "The Black Death killed an estimated 75-200 million people in the 14th century." },
    { category: "HISTORY", fact: "The first photograph ever taken required an 8-hour exposure time." },
    { category: "HISTORY", fact: "The Wright brothers' first flight lasted only 12 seconds." },

    { category: "SCIENCE", fact: "Bananas are radioactive. They contain potassium-40, a radioactive isotope of potassium, making them naturally radioactive." },
    { category: "SCIENCE", fact: "Water can exist in all three states of matter simultaneously at its triple point." },
    { category: "SCIENCE", fact: "Graphite and diamonds are made of the same element, carbon, but have completely different properties." },
    { category: "SCIENCE", fact: "Absolute zero (-273.15°C) is the coldest possible temperature where all molecular motion stops." },
    { category: "SCIENCE", fact: "Sound travels faster through water than through air, at about 1,500 meters per second." },
    { category: "SCIENCE", fact: "The speed of light is exactly 299,792,458 meters per second in a vacuum." },
    { category: "SCIENCE", fact: "Helium is the only element discovered in space before being found on Earth." },
    { category: "SCIENCE", fact: "A glass of water contains more molecules than there are glasses of water in all the world's oceans." },
    { category: "SCIENCE", fact: "Quantum entanglement allows particles to instantly affect each other regardless of distance." },
    { category: "SCIENCE", fact: "Time dilation means time passes slower at higher speeds and stronger gravitational fields." },
    { category: "SCIENCE", fact: "DNA is 99.9% identical between all humans, with only 0.1% accounting for individual differences." },
    { category: "SCIENCE", fact: "The human body contains the same elements found in stars, literally making us stardust." },
    { category: "SCIENCE", fact: "Photons have no mass but carry momentum and can exert pressure." },
    { category: "SCIENCE", fact: "Antimatter exists and is the most expensive substance on Earth at $25 billion per gram." },
    { category: "SCIENCE", fact: "The periodic table has 118 known elements, with new superheavy elements still being discovered." },
    { category: "SCIENCE", fact: "Lasers work by stimulating atoms to emit synchronized photons." },
    { category: "SCIENCE", fact: "Superconductors can levitate magnets and conduct electricity with zero resistance." },
    { category: "SCIENCE", fact: "The Higgs boson gives mass to other particles and was confirmed to exist in 2012." },
    { category: "SCIENCE", fact: "Nuclear fusion powers the Sun and all stars by converting hydrogen into helium." },
    { category: "SCIENCE", fact: "Radioactive decay is completely random and unpredictable for individual atoms." },

    { category: "ANIMALS", fact: "Sharks have been around longer than trees. Sharks evolved about 400 million years ago, while trees appeared around 350 million years ago." },
    { category: "ANIMALS", fact: "Honey bees can recognize human faces and remember them for several days." },
    { category: "ANIMALS", fact: "Dolphins have names for each other, using unique whistle signatures to identify individuals." },
    { category: "ANIMALS", fact: "Elephants can recognize themselves in mirrors, showing self-awareness like humans and great apes." },
    { category: "ANIMALS", fact: "A group of flamingos is called a 'flamboyance' and they can only eat with their heads upside down." },
    { category: "ANIMALS", fact: "Polar bears have black skin under their white fur to better absorb heat from the sun." },
    { category: "ANIMALS", fact: "Crows can use tools, solve complex puzzles, and even hold grudges against specific humans." },
    { category: "ANIMALS", fact: "A single bat can eat up to 1,000 mosquitoes in one hour." },
    { category: "ANIMALS", fact: "Penguins can jump up to 6 feet high out of the water." },
    { category: "ANIMALS", fact: "A shrimp's heart is located in its head." },
    { category: "ANIMALS", fact: "Tigers have striped skin, not just striped fur, and no two tigers have the same stripe pattern." },
    { category: "ANIMALS", fact: "Giraffes only need 5-30 minutes of sleep per day, often in short naps." },
    { category: "ANIMALS", fact: "A group of owls is called a 'parliament' and they can rotate their heads 270 degrees." },
    { category: "ANIMALS", fact: "Koalas sleep 20-22 hours per day and have fingerprints similar to humans." },
    { category: "ANIMALS", fact: "Hummingbirds are the only birds that can fly backwards and hover like helicopters." },
    { category: "ANIMALS", fact: "A lion's roar can be heard from up to 5 miles away." },
    { category: "ANIMALS", fact: "Sloths only defecate once per week and can lose up to 30% of their body weight doing so." },
    { category: "ANIMALS", fact: "Chameleons change color based on mood and temperature, not just for camouflage." },
    { category: "ANIMALS", fact: "A blue whale's heart weighs as much as a small car and is the size of a golf cart." },
    { category: "ANIMALS", fact: "Ants can lift 50 times their own body weight and work together to build complex societies." },

    { category: "TECHNOLOGY", fact: "The first computer bug was an actual bug. In 1947, Grace Hopper found a moth stuck in a computer relay, coining the term 'computer bug'." },
    { category: "TECHNOLOGY", fact: "The first hard drive in 1956 weighed over a ton and could store 5 megabytes of data." },
    { category: "TECHNOLOGY", fact: "Your smartphone has more computing power than all of NASA had when they landed on the moon." },
    { category: "TECHNOLOGY", fact: "The first webcam was created to monitor a coffee pot at Cambridge University." },
    { category: "TECHNOLOGY", fact: "Email was invented before the World Wide Web by Ray Tomlinson in 1971." },
    { category: "TECHNOLOGY", fact: "The first video uploaded to YouTube was titled 'Me at the zoo' and is still online today." },
    { category: "TECHNOLOGY", fact: "WiFi was originally called 'WaveLAN' and the term WiFi doesn't actually stand for anything." },
    { category: "TECHNOLOGY", fact: "The first computer mouse was made of wood and invented by Douglas Engelbart in 1964." },
    { category: "TECHNOLOGY", fact: "Bluetooth is named after King Harald Bluetooth, a 10th-century Danish king who united Danish tribes." },
    { category: "TECHNOLOGY", fact: "The QWERTY keyboard layout was designed to slow down typing to prevent mechanical jams." },
    { category: "TECHNOLOGY", fact: "The first AI program was created in 1951 and could play checkers." },
    { category: "TECHNOLOGY", fact: "3D printing was invented in 1983, but didn't become widely available until the 2000s." },
    { category: "TECHNOLOGY", fact: "The Internet was originally called ARPANET and connected just four computers in 1969." },
    { category: "TECHNOLOGY", fact: "GPS satellites must account for Einstein's theory of relativity to maintain accuracy." },
    { category: "TECHNOLOGY", fact: "The first digital camera was invented by Kodak in 1975 but took 23 seconds to capture one image." },
    { category: "TECHNOLOGY", fact: "Touch screens were invented in 1965, decades before smartphones made them popular." },
    { category: "TECHNOLOGY", fact: "The first programming language was created in 1843 by Ada Lovelace for Charles Babbage's Analytical Engine." },
    { category: "TECHNOLOGY", fact: "Fiber optic cables can transmit data at 70% the speed of light." },
    { category: "TECHNOLOGY", fact: "The first computer virus was called 'Creeper' and was created in 1971 as an experiment." },
    { category: "TECHNOLOGY", fact: "Quantum computers use qubits that can exist in multiple states simultaneously, unlike classical bits." },

    { category: "FOOD", fact: "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible." },
    { category: "FOOD", fact: "Chocolate was once used as currency by the Aztecs, and cocoa beans were more valuable than gold." },
    { category: "FOOD", fact: "Peanuts aren't actually nuts; they're legumes that grow underground like peas and beans." },
    { category: "FOOD", fact: "Vanilla is the second most expensive spice in the world after saffron." },
    { category: "FOOD", fact: "Tomatoes were once considered poisonous by Europeans because wealthy people got lead poisoning from tomato acid leaching lead from their pewter plates." },
    { category: "FOOD", fact: "Carrots were originally purple, not orange, and only became orange through selective breeding in the Netherlands." },
    { category: "FOOD", fact: "Lobsters were once considered peasant food and were so abundant they were fed to prisoners." },
    { category: "FOOD", fact: "Avocados are actually fruits, specifically berries, and are toxic to most animals except humans." },
    { category: "FOOD", fact: "The spiciness of chili peppers is measured in Scoville Heat Units, named after Wilbur Scoville." },
    { category: "FOOD", fact: "Cashews grow on the bottom of cashew apples and are technically seeds, not nuts." },
    { category: "FOOD", fact: "Bananas are berries, but strawberries aren't. Botanically, berries must have seeds inside their flesh." },
    { category: "FOOD", fact: "White chocolate isn't actually chocolate because it contains no cocoa solids." },
    { category: "FOOD", fact: "Apples float in water because they are 25% air by volume." },
    { category: "FOOD", fact: "Ketchup was sold as medicine in the 1830s to treat indigestion and other ailments." },
    { category: "FOOD", fact: "Pistachios can spontaneously combust when stored in large quantities due to their high fat content." },
    { category: "FOOD", fact: "Fortune cookies were actually invented in San Francisco, not China." },
    { category: "FOOD", fact: "Ripe cranberries will bounce like rubber balls due to air pockets inside them." },
    { category: "FOOD", fact: "Oysters can change gender multiple times throughout their lives." },
    { category: "FOOD", fact: "The holes in Swiss cheese are called 'eyes' and are formed by bacteria that release carbon dioxide." },
    { category: "FOOD", fact: "Spam stands for 'Specially Processed American Meat' and over 8 billion cans have been sold worldwide." },

    { category: "HUMAN BODY", fact: "Your brain uses 20% of your body's total energy despite being only 2% of your body weight." },
    { category: "HUMAN BODY", fact: "You have about 37.2 trillion cells in your body, and they're constantly being replaced." },
    { category: "HUMAN BODY", fact: "Your stomach gets an entirely new lining every 3-5 days because stomach acid would otherwise digest it." },
    { category: "HUMAN BODY", fact: "Humans shed about 40,000 dead skin cells every minute, or about 9 pounds per year." },
    { category: "HUMAN BODY", fact: "Your heart beats about 100,000 times per day and pumps 2,000 gallons of blood." },
    { category: "HUMAN BODY", fact: "Humans are the only animals that blush, and it happens because of emotional responses." },
    { category: "HUMAN BODY", fact: "Your bones are stronger than steel pound for pound, yet they're mostly made of calcium and phosphorus." },
    { category: "HUMAN BODY", fact: "The human eye can distinguish about 10 million different colors." },
    { category: "HUMAN BODY", fact: "Your liver can regenerate itself completely even if 75% of it is removed." },
    { category: "HUMAN BODY", fact: "Fingernails grow about four times faster than toenails." },
    { category: "HUMAN BODY", fact: "The human brain contains approximately 86 billion neurons connected by trillions of synapses." },
    { category: "HUMAN BODY", fact: "Your taste buds are replaced every 7-10 days throughout your entire life." },
    { category: "HUMAN BODY", fact: "Humans have a unique scent print, similar to fingerprints, that dogs can detect." },
    { category: "HUMAN BODY", fact: "The muscles that control your eyes move more than 100,000 times per day." },
    { category: "HUMAN BODY", fact: "Your lungs contain about 300-500 million tiny air sacs called alveoli." },
    { category: "HUMAN BODY", fact: "The human skeleton completely replaces itself every 10 years through bone remodeling." },
    { category: "HUMAN BODY", fact: "Your appendix isn't useless; it serves as a reservoir for beneficial gut bacteria." },
    { category: "HUMAN BODY", fact: "Humans can survive weeks without food but only days without water." },
    { category: "HUMAN BODY", fact: "The longest bone in your body is the femur, and the smallest is the stapes in your ear." },
    { category: "HUMAN BODY", fact: "Your brain doesn't have pain receptors, which is why brain surgery can be performed while awake." },

    { category: "PHYSICS", fact: "Time moves slower for your feet than your head due to gravitational time dilation." },
    { category: "PHYSICS", fact: "Quantum tunneling allows particles to pass through barriers that should be impossible to cross." },
    { category: "PHYSICS", fact: "The uncertainty principle states you cannot know both the position and momentum of a particle simultaneously." },
    { category: "PHYSICS", fact: "Dark matter makes up 85% of all matter in the universe but doesn't interact with light." },
    { category: "PHYSICS", fact: "At the event horizon of a black hole, time appears to stop from an outside observer's perspective." },
    { category: "PHYSICS", fact: "Wave-particle duality means light and matter can behave as both waves and particles." },
    { category: "PHYSICS", fact: "Zero-point energy means even empty space contains energy due to quantum fluctuations." },
    { category: "PHYSICS", fact: "String theory suggests that fundamental particles are actually vibrating one-dimensional strings." },
    { category: "PHYSICS", fact: "The speed of light in a vacuum is constant regardless of the observer's reference frame." },
    { category: "PHYSICS", fact: "Magnetic monopoles have never been observed despite being predicted by some theories." },
    { category: "PHYSICS", fact: "Superfluids can flow without friction and climb up the walls of containers." },
    { category: "PHYSICS", fact: "The double-slit experiment shows that observation affects the behavior of quantum particles." },
    { category: "PHYSICS", fact: "Wormholes are theoretical tunnels through spacetime that could connect distant regions of the universe." },
    { category: "PHYSICS", fact: "The Casimir effect shows that empty space exerts pressure due to quantum field fluctuations." },
    { category: "PHYSICS", fact: "General relativity predicts that massive objects bend spacetime, causing what we perceive as gravity." },
    { category: "PHYSICS", fact: "Schrödinger's cat illustrates quantum superposition where particles exist in multiple states simultaneously." },
    { category: "PHYSICS", fact: "The many-worlds interpretation suggests every quantum measurement creates parallel universes." },
    { category: "PHYSICS", fact: "Hawking radiation means black holes slowly evaporate by emitting particles." },
    { category: "PHYSICS", fact: "The cosmic microwave background is leftover radiation from the Big Bang, detectable throughout the universe." },
    { category: "PHYSICS", fact: "Antimatter particles have opposite charges and annihilate with matter, releasing pure energy." },

    { category: "OCEAN", fact: "The ocean contains 99% of Earth's living space, yet we've explored less than 5% of it." },
    { category: "OCEAN", fact: "The deepest part of the ocean, Challenger Deep, could fit Mount Everest with over a mile to spare." },
    { category: "OCEAN", fact: "Ocean currents act like a global conveyor belt, distributing heat around the planet." },
    { category: "OCEAN", fact: "The Great Pacific Garbage Patch is twice the size of Texas and consists mostly of microplastics." },
    { category: "OCEAN", fact: "Coral reefs support 25% of all marine species despite covering less than 1% of the ocean floor." },
    { category: "OCEAN", fact: "The ocean produces over 50% of the world's oxygen through phytoplankton photosynthesis." },
    { category: "OCEAN", fact: "Sound travels 4 times faster in water than in air, allowing whales to communicate across vast distances." },
    { category: "OCEAN", fact: "The ocean contains enough salt to cover all land on Earth in a layer 500 feet thick." },
    { category: "OCEAN", fact: "Underwater rivers exist where dense salt water flows beneath less dense fresh water." },
    { category: "OCEAN", fact: "The ocean's midnight zone is the largest living space on Earth but receives no sunlight." },
    { category: "OCEAN", fact: "Tidal forces from the Moon create two high tides and two low tides every day." },
    { category: "OCEAN", fact: "The ocean contains dissolved gold, but it would cost more to extract than the gold is worth." },
    { category: "OCEAN", fact: "Hydrothermal vents on the ocean floor support life without any sunlight." },
    { category: "OCEAN", fact: "The ocean's thermohaline circulation takes about 1,000 years to complete one full cycle." },
    { category: "OCEAN", fact: "Bioluminescent organisms create 80% of the light in the deep ocean." },
    { category: "OCEAN", fact: "Submarine canyons on the ocean floor are larger and deeper than the Grand Canyon." },
    { category: "OCEAN", fact: "The ocean absorbs 25% of all carbon dioxide produced by human activities." },
    { category: "OCEAN", fact: "Pressure at the bottom of the ocean is over 1,000 times greater than at sea level." },
    { category: "OCEAN", fact: "Ocean waves can travel thousands of miles across open water without losing much energy." },
    { category: "OCEAN", fact: "The ocean contains more than 20 million tons of dissolved gold." },

    { category: "BIOLOGY", fact: "Your DNA is 99.9% identical to every other human's DNA, with only 0.1% making you unique." },
    { category: "BIOLOGY", fact: "Tardigrades can survive in space, extreme temperatures, and radiation that would kill most life forms." },
    { category: "BIOLOGY", fact: "Mitochondria have their own DNA separate from your cell's DNA because they were once independent bacteria." },
    { category: "BIOLOGY", fact: "The human genome contains about 3 billion base pairs but only 2% codes for proteins." },
    { category: "BIOLOGY", fact: "Bacteria have been evolving for 3.5 billion years and can adapt to almost any environment." },
    { category: "BIOLOGY", fact: "Your body contains roughly the same number of bacterial cells as human cells." },
    { category: "BIOLOGY", fact: "Viruses are not technically alive because they cannot reproduce without a host cell." },
    { category: "BIOLOGY", fact: "Photosynthesis converts light energy into chemical energy that powers most life on Earth." },
    { category: "BIOLOGY", fact: "Evolution doesn't have a goal; it's simply the result of random mutations and natural selection." },
    { category: "BIOLOGY", fact: "The first life on Earth appeared about 3.8 billion years ago in the form of simple microorganisms." },
    { category: "BIOLOGY", fact: "Cellular respiration is the opposite of photosynthesis, breaking down glucose to release energy." },
    { category: "BIOLOGY", fact: "Enzyme catalysts can speed up chemical reactions by factors of millions or billions." },
    { category: "BIOLOGY", fact: "The longest-living organisms are certain bacteria that can survive for millions of years." },
    { category: "BIOLOGY", fact: "Genetic mutations occur naturally at a rate of about 100-200 mutations per genome per generation." },
    { category: "BIOLOGY", fact: "Symbiosis allows different species to live together in mutually beneficial relationships." },
    { category: "BIOLOGY", fact: "Homeostasis maintains stable internal conditions despite changing external environments." },
    { category: "BIOLOGY", fact: "The diversity of life on Earth includes an estimated 8.7 million species." },
    { category: "BIOLOGY", fact: "Protein folding determines function, and misfolded proteins can cause diseases." },
    { category: "BIOLOGY", fact: "Biological clocks regulate daily rhythms in almost all living organisms." },
    { category: "BIOLOGY", fact: "Sexual reproduction increases genetic diversity, which helps species adapt to changing environments." },

    { category: "GEOGRAPHY", fact: "Russia spans 11 time zones, more than any other country in the world." },
    { category: "GEOGRAPHY", fact: "The Pacific Ocean is larger than all land masses on Earth combined." },
    { category: "GEOGRAPHY", fact: "Mount Everest grows about 4 millimeters taller each year due to tectonic plate movement." },
    { category: "GEOGRAPHY", fact: "Antarctica is both the driest and windiest continent, with winds reaching 200 mph." },
    { category: "GEOGRAPHY", fact: "The Sahara Desert is roughly the size of the entire United States." },
    { category: "GEOGRAPHY", fact: "Iceland sits on the Mid-Atlantic Ridge where two tectonic plates are slowly separating." },
    { category: "GEOGRAPHY", fact: "The Dead Sea is the lowest point on Earth's surface at 1,412 feet below sea level." },
    { category: "GEOGRAPHY", fact: "Australia is the only country that is also a continent." },
    { category: "GEOGRAPHY", fact: "The Amazon River is longer than the distance from New York to Rome." },
    { category: "GEOGRAPHY", fact: "Vatican City is the smallest country in the world at only 0.17 square miles." },
    { category: "GEOGRAPHY", fact: "The Ring of Fire contains 75% of the world's active volcanoes." },
    { category: "GEOGRAPHY", fact: "Lake Baikal contains 20% of the world's unfrozen fresh water." },
    { category: "GEOGRAPHY", fact: "The Mariana Trench is deeper than Mount Everest is tall." },
    { category: "GEOGRAPHY", fact: "Africa is splitting apart along the East African Rift, eventually forming a new ocean." },
    { category: "GEOGRAPHY", fact: "The equator passes through 13 countries across three continents." },
    { category: "GEOGRAPHY", fact: "Greenland is the world's largest island but has a population smaller than most cities." },
    { category: "GEOGRAPHY", fact: "The Atacama Desert in Chile is the driest non-polar desert in the world." },
    { category: "GEOGRAPHY", fact: "The Himalayas are still growing as the Indian plate continues to push into Asia." },
    { category: "GEOGRAPHY", fact: "Madagascar is the fourth largest island in the world and has unique wildlife found nowhere else." },
    { category: "GEOGRAPHY", fact: "The Caspian Sea is actually the world's largest lake, not a sea." },

    { category: "PSYCHOLOGY", fact: "The mere exposure effect causes people to develop preferences for things they're familiar with." },
    { category: "PSYCHOLOGY", fact: "Confirmation bias leads people to seek information that confirms their existing beliefs." },
    { category: "PSYCHOLOGY", fact: "The placebo effect can cause real physical improvements in health through belief alone." },
    { category: "PSYCHOLOGY", fact: "Cognitive dissonance occurs when people hold contradictory beliefs or attitudes simultaneously." },
    { category: "PSYCHOLOGY", fact: "False memories can feel as real as true memories and can be implanted through suggestion." },
    { category: "PSYCHOLOGY", fact: "The bystander effect makes people less likely to help when others are present." },
    { category: "PSYCHOLOGY", fact: "Dopamine is released in anticipation of rewards, not just when receiving them." },
    { category: "PSYCHOLOGY", fact: "Multitasking is actually task-switching and reduces efficiency and accuracy." },
    { category: "PSYCHOLOGY", fact: "The Dunning-Kruger effect causes incompetent people to overestimate their abilities." },
    { category: "PSYCHOLOGY", fact: "Mirror neurons fire both when performing an action and when observing others perform the same action." },
    { category: "PSYCHOLOGY", fact: "Sleep is essential for memory consolidation and transferring information from short-term to long-term memory." },
    { category: "PSYCHOLOGY", fact: "Emotional memories are stored differently than factual memories and can feel more vivid." },
    { category: "PSYCHOLOGY", fact: "The average person makes about 35,000 decisions per day." },
    { category: "PSYCHOLOGY", fact: "Social anxiety affects about 12% of the population at some point in their lives." },
    { category: "PSYCHOLOGY", fact: "Humans have a negativity bias, paying more attention to negative information than positive." },
    { category: "PSYCHOLOGY", fact: "The brain's plasticity allows it to reorganize and form new neural connections throughout life." },
    { category: "PSYCHOLOGY", fact: "Flow state occurs when people are fully immersed in activities and lose track of time." },
    { category: "PSYCHOLOGY", fact: "Priming can influence behavior and decisions without conscious awareness." },
    { category: "PSYCHOLOGY", fact: "The spotlight effect causes people to overestimate how much others notice their mistakes." },
    { category: "PSYCHOLOGY", fact: "Meditation can physically change brain structure and improve emotional regulation." },

    { category: "MUSIC", fact: "Mozart composed over 600 pieces of music in his short 35-year life." },
    { category: "MUSIC", fact: "The violin has remained virtually unchanged for over 400 years since its perfection in Italy." },
    { category: "MUSIC", fact: "Beethoven composed some of his greatest works while completely deaf." },
    { category: "MUSIC", fact: "The piano has 88 keys: 52 white keys and 36 black keys." },
    { category: "MUSIC", fact: "Music therapy can help treat depression, anxiety, and even physical pain." },
    { category: "MUSIC", fact: "The oldest musical instrument is the flute, dating back at least 40,000 years." },
    { category: "MUSIC", fact: "Perfect pitch occurs in less than 1% of the population and may be genetic." },
    { category: "MUSIC", fact: "The human ear can distinguish between frequencies as close as 0.1% apart." },
    { category: "MUSIC", fact: "Baroque music was designed to evoke specific emotions in listeners." },
    { category: "MUSIC", fact: "The major scale contains seven different notes that repeat in octaves." },
    { category: "MUSIC", fact: "Stradivarius violins are still considered the finest ever made, crafted 300 years ago." },
    { category: "MUSIC", fact: "Music can trigger the release of dopamine, the same neurotransmitter involved in addiction." },
    { category: "MUSIC", fact: "The metronome was invented in 1812 to help musicians keep consistent tempo." },
    { category: "MUSIC", fact: "Gregorian chant was the dominant form of church music for over 1,000 years." },
    { category: "MUSIC", fact: "The harmonic series explains why certain musical intervals sound pleasing together." },
    { category: "MUSIC", fact: "Jazz originated in New Orleans by blending African rhythms with European harmonies." },
    { category: "MUSIC", fact: "The human voice is considered the most versatile musical instrument." },
    { category: "MUSIC", fact: "Electronic music synthesis began in the 1950s with experimental computer programs." },
    { category: "MUSIC", fact: "Sound waves travel at 343 meters per second through air at room temperature." },
    { category: "MUSIC", fact: "The accordion is considered the most difficult instrument to master due to its complexity." },

    { category: "SPORTS", fact: "A marathon is exactly 26.2 miles because of the 1908 London Olympics route adjustment." },
    { category: "SPORTS", fact: "Golf balls have dimples because they fly farther than smooth balls due to aerodynamics." },
    { category: "SPORTS", fact: "Basketball was invented in 1891 using peach baskets as goals." },
    { category: "SPORTS", fact: "The Olympic rings represent the five inhabited continents of the world." },
    { category: "SPORTS", fact: "Tennis scoring (15, 30, 40) may derive from medieval French gambling odds." },
    { category: "SPORTS", fact: "Soccer is the most popular sport globally, played by over 250 million people." },
    { category: "SPORTS", fact: "The first modern Olympics in 1896 had only 43 events compared to over 300 today." },
    { category: "SPORTS", fact: "Baseball's 'seventh inning stretch' tradition began in 1910 when President Taft stood to stretch." },
    { category: "SPORTS", fact: "Swimming is one of the few sports that exercises every major muscle group." },
    { category: "SPORTS", fact: "The fastest recorded tennis serve was 163.7 mph by Sam Groth in 2012." },
    { category: "SPORTS", fact: "Hockey pucks are frozen before games to reduce bouncing and increase control." },
    { category: "SPORTS", fact: "Formula 1 drivers experience G-forces up to 5 times greater than Earth's gravity." },
    { category: "SPORTS", fact: "The longest recorded ski jump is over 800 feet, nearly the length of three football fields." },
    { category: "SPORTS", fact: "Ping-pong balls are 40mm in diameter and must weigh exactly 2.7 grams for competition." },
    { category: "SPORTS", fact: "The pole vault world record has increased by over 6 feet since the 1950s due to better poles." },
    { category: "SPORTS", fact: "Professional cyclists can generate over 400 watts of power during sprint finishes." },
    { category: "SPORTS", fact: "Boxing gloves actually cause more brain damage than bare-knuckle fighting by allowing harder punches." },
    { category: "SPORTS", fact: "The fastest recorded punch in boxing measured 45 mph." },
    { category: "SPORTS", fact: "Rock climbing has been an Olympic sport since 2020, combining speed, bouldering, and lead climbing." },
    { category: "SPORTS", fact: "The FIFA World Cup is watched by over 3 billion people, making it the most viewed sporting event." },

    { category: "LITERATURE", fact: "Shakespeare invented over 1,700 words that we still use today, including 'assassination' and 'lonely'." },
    { category: "LITERATURE", fact: "The longest novel ever written is 'In Search of Lost Time' by Marcel Proust at over 4,000 pages." },
    { category: "LITERATURE", fact: "Dr. Seuss wrote 'Green Eggs and Ham' using only 50 different words to win a bet." },
    { category: "LITERATURE", fact: "The Great Gatsby was initially a commercial failure and Fitzgerald died thinking it was a flop." },
    { category: "LITERATURE", fact: "J.K. Rowling was rejected by 12 publishers before Harry Potter was accepted." },
    { category: "LITERATURE", fact: "The oldest known work of literature is the Epic of Gilgamesh, written around 2100 BC." },
    { category: "LITERATURE", fact: "Ernest Hemingway wrote standing up at a chest-high bookshelf converted to a desk." },
    { category: "LITERATURE", fact: "The word 'bookworm' originally referred to actual insects that ate through book pages." },
    { category: "LITERATURE", fact: "Agatha Christie is the most translated author in the world after the Bible." },
    { category: "LITERATURE", fact: "Mark Twain was born and died in years when Halley's Comet was visible, as he predicted." },
    { category: "LITERATURE", fact: "The printing press made books affordable and led to widespread literacy in Europe." },
    { category: "LITERATURE", fact: "Edgar Allan Poe invented the detective fiction genre with 'The Murders in the Rue Morgue'." },
    { category: "LITERATURE", fact: "Haiku poetry follows a 5-7-5 syllable pattern and originated in Japan." },
    { category: "LITERATURE", fact: "George Orwell's '1984' introduced terms like 'Big Brother' and 'thoughtcrime' into common language." },
    { category: "LITERATURE", fact: "The first novel is considered to be 'The Tale of Genji' written in Japan around 1000 AD." },
    { category: "LITERATURE", fact: "Charles Dickens was paid by the word, which explains his lengthy, descriptive writing style." },
    { category: "LITERATURE", fact: "The Oxford English Dictionary contains over 170,000 current English words." },
    { category: "LITERATURE", fact: "Maya Angelou memorized entire books and recited them to develop her exceptional memory." },
    { category: "LITERATURE", fact: "The Brothers Grimm collected and published over 200 folk tales, including Cinderella and Snow White." },
    { category: "LITERATURE", fact: "Science fiction predicted many modern technologies like submarines, satellites, and tablets." },

    { category: "MATHEMATICS", fact: "Pi is an infinite, non-repeating decimal that has been calculated to over 70 trillion digits." },
    { category: "MATHEMATICS", fact: "The number zero wasn't invented until around 500 AD and revolutionized mathematics." },
    { category: "MATHEMATICS", fact: "There are more possible arrangements of a deck of cards than there are atoms on Earth." },
    { category: "MATHEMATICS", fact: "The Fibonacci sequence appears everywhere in nature, from flower petals to galaxy spirals." },
    { category: "MATHEMATICS", fact: "Euler's identity (e^(iπ) + 1 = 0) connects five fundamental mathematical constants." },
    { category: "MATHEMATICS", fact: "The concept of infinity has different sizes; some infinities are larger than others." },
    { category: "MATHEMATICS", fact: "Prime numbers become increasingly rare as numbers get larger but never completely disappear." },
    { category: "MATHEMATICS", fact: "The Monty Hall problem shows that switching doors gives you a 2/3 chance of winning." },
    { category: "MATHEMATICS", fact: "Fractal geometry describes irregular shapes that repeat patterns at every scale." },
    { category: "MATHEMATICS", fact: "The golden ratio (1.618...) appears in art, architecture, and nature throughout history." },
    { category: "MATHEMATICS", fact: "Gödel's incompleteness theorems proved that some mathematical truths cannot be proven." },
    { category: "MATHEMATICS", fact: "Imaginary numbers are essential for describing real-world phenomena like electrical circuits." },
    { category: "MATHEMATICS", fact: "Calculus was independently invented by Newton and Leibniz around the same time." },
    { category: "MATHEMATICS", fact: "The four-color theorem states that any map can be colored with only four colors." },
    { category: "MATHEMATICS", fact: "Statistics can prove correlation but correlation does not imply causation." },
    { category: "MATHEMATICS", fact: "Topology studies properties of space that are preserved under continuous deformations." },
    { category: "MATHEMATICS", fact: "The birthday paradox shows that 23 people have a 50% chance of sharing a birthday." },
    { category: "MATHEMATICS", fact: "Game theory analyzes strategic decision-making between rational players." },
    { category: "MATHEMATICS", fact: "Chaos theory explains how small changes can lead to dramatically different outcomes." },
    { category: "MATHEMATICS", fact: "Knot theory is a branch of mathematics that studies mathematical knots in three-dimensional space." },

    { category: "MEDICINE", fact: "Aspirin comes from willow bark and has been used for pain relief for over 2,000 years." },
    { category: "MEDICINE", fact: "Anesthesia revolutionized surgery, making complex operations possible without pain." },
    { category: "MEDICINE", fact: "Antibiotics have saved more lives than any other medical discovery in history." },
    { category: "MEDICINE", fact: "The human immune system can recognize and remember millions of different pathogens." },
    { category: "MEDICINE", fact: "Vaccines work by training your immune system to recognize and fight specific diseases." },
    { category: "MEDICINE", fact: "The placebo effect can cause real physiological changes through the power of belief." },
    { category: "MEDICINE", fact: "X-rays were discovered accidentally by Wilhelm Röntgen while experimenting with electron beams." },
    { category: "MEDICINE", fact: "The first successful heart transplant was performed in 1967 by Dr. Christiaan Barnard." },
    { category: "MEDICINE", fact: "Insulin was discovered in 1922, turning type 1 diabetes from fatal to manageable." },
    { category: "MEDICINE", fact: "The double helix structure of DNA was discovered using X-ray crystallography." },
    { category: "MEDICINE", fact: "Organ transplantation requires immunosuppressive drugs to prevent rejection." },
    { category: "MEDICINE", fact: "The blood-brain barrier protects the brain from toxins but also blocks many medications." },
    { category: "MEDICINE", fact: "Gene therapy can potentially cure genetic diseases by replacing faulty genes." },
    { category: "MEDICINE", fact: "The microbiome in your gut affects digestion, immunity, and even mental health." },
    { category: "MEDICINE", fact: "Cancer cells divide uncontrollably because they ignore normal growth regulation signals." },
    { category: "MEDICINE", fact: "Stem cells can differentiate into any type of cell in the human body." },
    { category: "MEDICINE", fact: "The stethoscope was invented in 1816 to allow doctors to listen to heartbeats modestly." },
    { category: "MEDICINE", fact: "MRI machines use powerful magnetic fields to create detailed images of internal organs." },
    { category: "MEDICINE", fact: "Surgical robots can perform operations with precision impossible for human hands." },
    { category: "MEDICINE", fact: "Personalized medicine tailors treatments based on individual genetic profiles." },

    { category: "ARCHAEOLOGY", fact: "Archaeologists use carbon dating to determine the age of organic materials up to 50,000 years old." },
    { category: "ARCHAEOLOGY", fact: "The Rosetta Stone was key to deciphering Egyptian hieroglyphics after being lost for centuries." },
    { category: "ARCHAEOLOGY", fact: "Pompeii was preserved by volcanic ash, providing a perfect snapshot of Roman life in 79 AD." },
    { category: "ARCHAEOLOGY", fact: "King Tutankhamun's tomb is the most intact pharaoh's tomb ever discovered." },
    { category: "ARCHAEOLOGY", fact: "Stonehenge took over 1,500 years to build and its purpose remains partially mysterious." },
    { category: "ARCHAEOLOGY", fact: "The Terracotta Army contains over 8,000 life-sized soldiers guarding China's first emperor." },
    { category: "ARCHAEOLOGY", fact: "Machu Picchu was built without mortar, using precisely cut stones that fit together perfectly." },
    { category: "ARCHAEOLOGY", fact: "The Dead Sea Scrolls are the oldest known copies of Hebrew Bible texts." },
    { category: "ARCHAEOLOGY", fact: "Ground-penetrating radar allows archaeologists to see buried structures without excavating." },
    { category: "ARCHAEOLOGY", fact: "Dendrochronology uses tree rings to date wooden artifacts and climate patterns." },
    { category: "ARCHAEOLOGY", fact: "The Antikythera mechanism is an ancient Greek analog computer from around 100 BC." },
    { category: "ARCHAEOLOGY", fact: "Çatalhöyük is one of the world's first towns, inhabited 9,000 years ago in Turkey." },
    { category: "ARCHAEOLOGY", fact: "The Venus de Milo originally had arms, but they were lost over time." },
    { category: "ARCHAEOLOGY", fact: "Archaeologists use stratigraphy to determine the relative age of artifacts by their soil layers." },
    { category: "ARCHAEOLOGY", fact: "The Iceman Ötzi is a 5,300-year-old mummy that provides insights into Copper Age life." },
    { category: "ARCHAEOLOGY", fact: "LiDAR technology can reveal hidden archaeological sites beneath dense forest canopies." },
    { category: "ARCHAEOLOGY", fact: "The Library of Alexandria was the largest library in the ancient world." },
    { category: "ARCHAEOLOGY", fact: "Underwater archaeology explores shipwrecks and submerged cities." },
    { category: "ARCHAEOLOGY", fact: "The Nazca Lines are massive geoglyphs in Peru that can only be fully appreciated from the air." },
    { category: "ARCHAEOLOGY", fact: "Easter Island's moai statues have full bodies buried underground." },

    { category: "CHEMISTRY", fact: "Water is the only substance that's less dense as a solid than as a liquid, which is why ice floats." },
    { category: "CHEMISTRY", fact: "Noble gases are called 'noble' because they rarely react with other elements." },
    { category: "CHEMISTRY", fact: "Diamond is the hardest natural substance, but graphite (also carbon) is one of the softest." },
    { category: "CHEMISTRY", fact: "The periodic table organizes elements by their atomic number and electron configuration." },
    { category: "CHEMISTRY", fact: "Chemical bonds form when atoms share or transfer electrons to achieve stable electron shells." },
    { category: "CHEMISTRY", fact: "Catalysts speed up chemical reactions without being consumed in the process." },
    { category: "CHEMISTRY", fact: "pH stands for 'potential of Hydrogen' and measures acidity on a scale from 0 to 14." },
    { category: "CHEMISTRY", fact: "Polymers are large molecules made of repeating units, like DNA, proteins, and plastics." },
    { category: "CHEMISTRY", fact: "The Maillard reaction creates the brown color and complex flavors in cooked foods." },
    { category: "CHEMISTRY", fact: "Isomers are compounds with the same molecular formula but different structures and properties." },
    { category: "CHEMISTRY", fact: "Supercritical fluids have properties between liquids and gases and are used in decaffeination." },
    { category: "CHEMISTRY", fact: "Electronegativity determines how atoms share electrons in chemical bonds." },
    { category: "CHEMISTRY", fact: "Chirality means molecules can exist in left and right-handed forms with different properties." },
    { category: "CHEMISTRY", fact: "Le Chatelier's principle predicts how chemical equilibria respond to changes in conditions." },
    { category: "CHEMISTRY", fact: "Thermodynamics governs all chemical reactions and determines whether they can occur spontaneously." },
    { category: "CHEMISTRY", fact: "Spectroscopy identifies substances by analyzing how they interact with electromagnetic radiation." },
    { category: "CHEMISTRY", fact: "Crystallography reveals the three-dimensional structure of molecules and materials." },
    { category: "CHEMISTRY", fact: "Organic chemistry studies carbon-based compounds, which form the basis of all life." },
    { category: "CHEMISTRY", fact: "Enzymes are biological catalysts that enable life-sustaining chemical reactions." },
    { category: "CHEMISTRY", fact: "The greenhouse effect occurs when certain gases trap heat in Earth's atmosphere." }
];